name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    - run: pip install -r requirements.txt
    - run: ./lint.sh
    - run: pytest --cov=. --cov-report=xml
    - uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
